apiVersion: v1
kind: Namespace
metadata:
  name: app1namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace : app1namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: manish225/fynd_app1:f1
        
        imagePullPolicy: Always  
        env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                    fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                    fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                    fieldPath: status.podIP
        ports:
        - containerPort: 8000
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
