apiVersion: v1
kind: Service
metadata:
  name: app1
  labels:
    app: app1
  namespace : app1namespace
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30080
  selector:
    app: app1