apiVersion: v1
kind: Namespace
metadata:
  name: app2namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace : app2namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: gcr.io/golden-memory-292205/app2_fynd:v1
        imagePullPolicy: Always
        env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                    fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                    fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                    fieldPath: status.podIP
        ports:
        - containerPort: 8001
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 8001
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 8001
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
