apiVersion: v1
kind: Service
metadata:
  name: app2
  labels:
    app: app2
  namespace : app2namespace
spec:
  type: LoadBalancer
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8001
    nodePort: 30081
  selector:
    app: app2
