apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-resource-app1
  namespace: app1namespace
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: app1
          servicePort: 8000
